import{a as b,i as w,S as L}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",q="46859075-3fccd495eb65e9407cc96c329";async function v(t,o=1,n=15){const s={key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:n};try{return(await b(S,{params:s})).data}catch{throw new Error("Error fetching images")}}function E(t,o){const n=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:a,views:m,comments:h,downloads:g})=>`
    <a class="gallery-item" href="${e}">
      <img src="${s}" alt="${r}" loading="lazy"/>
      <div class="info">
        <p><b>Likes:</b> ${a}</p>
        <p><b>Views:</b> ${m}</p>
        <p><b>Comments:</b> ${h}</p>
        <p><b>Downloads:</b> ${g}</p>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",n)}function u(t){w.show({message:t,position:"topRight",timeout:3e3})}function P(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}let d="",i=1,c=0;const $=document.querySelector(".form"),y=document.querySelector(".gallery"),l=document.querySelector(".js-load-more"),f=document.querySelector(".loader"),O=new L(".gallery a",{captionsData:"alt",captionDelay:250});$.addEventListener("submit",t=>{t.preventDefault(),d=t.currentTarget.elements.query.value.trim(),d&&(i=1,c=0,y.innerHTML="",l.style.display="none",p())});l.addEventListener("click",()=>{i+=1,p()});async function p(){f.style.display="block";try{const{hits:t,totalHits:o}=await v(d,i);if(i===1&&(c=o,o===0)){u("Sorry, there are no images matching your search query. Please try again!");return}E(t,y),O.refresh(),t.length===15&&i*15<c?l.style.display="block":(l.style.display="none",i*15>=c&&u("We're sorry, but you've reached the end of search results.")),i>1&&P()}catch{u("Failed to load images. Please try again later.")}finally{f.style.display="none"}}
//# sourceMappingURL=index.js.map
